INSERT INTO Soda VALUES(1, 'Budweiser','BUDWEISER',10);
INSERT INTO Soda VALUES(2, 'Cola-Cola','COCACOLA',8);
INSERT INTO Soda VALUES(3, 'Pepsi','PEPSI',9);
INSERT INTO Soda VALUES(4, 'Pepsi lemonm','PEPSI',9);
INSERT INTO Soda VALUES(5, 'Cola-Cola Light','COCACOLA',18);
INSERT INTO Soda VALUES(6, 'Pepsi Max','PEPSI',12);